{{- $python := .Values.apiPython -}}
{{- $go := .Values.apiGo -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "blog-app.name" . }}-api-python-secret
  labels:
    {{- include "blog-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  API_TOKEN: {{ $python.secretToken | default "example-token" | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "blog-app.name" . }}-api-go-secret
  labels:
    {{- include "blog-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  SHARED_SECRET: {{ $go.secretToken | default "example-secret" | quote }}
