apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: blog-app
  namespace: blog-app
spec:
  interval: 5m0s
  releaseName: blog-app
  chart:
    spec:
      chart: ./charts/blog-app
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m0s
  values:
    ingress:
      enabled: true
      className: nginx
      host: example.local
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-staging
      tls:
        enabled: true
        secretName: blog-app-tls
    apiPython:
      image:
        repository: ghcr.io/fabdev10/api-python
        tag: latest
    apiGo:
      image:
        repository: ghcr.io/fabdev10/api-go
        tag: latest
