apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: gitops-lab
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/Fabdev10/gitops-lab.git
  branch: main
